### ISSUE TITLE
yum install shoal-client failing -- please run createrepo

### ISSUE THREAD

**Issue by DrDaveD** [hep-gc/shoal#145]
While following the instructions in shoal-agent/README.md, on an sl6 machine I get an error: 
```
warning: rpmts_HdrFromFdno: Header V4 DSA/SHA1 Signature, key ID b4833a14: NOKEY


Public key for shoal-client-0.5.0-1.noarch.rpm is not installed
```
and on an sl7 machine I get the error:
Downloading packages:
shoal-client-0.6.4-1.el7.cento FAILED                                          
http://shoal.heprc.uvic.ca/repo/sl7x/prod/noarch/shoal-client-0.6.4-1.el7.centos.noarch.rpm: [Errno 14] HTTP Error 404 - Not Found
```
Indeed, there's a shoal-client-0.6.5-1.el7.centos.noarch.rpm which has been there since 25-Oct-2017.  Has nobody run createrepo since then?

There's also a shoal-client-0.6.5-1.el6.noarch.rpm for el7, but again the repodata is too old.  In an x86_64 directory there's a shoal-client-0.5.0-1.noarch.rpm which must be where the el6 error is coming from.

**Comment by colsond** [comment]
Hi Dave, I had a close look at our repo and noticed a lot of issues. We've dealt with a lot of the out of date repo info and updated the dependency list for the sl6 rpms. We were able to install successfully using the instructions for both sl6, and sl7.

Please let us know if you continue to see issues but the two above issues should be fixed.

**Comment by DrDaveD** [comment]
Colson,

sl6 is working better now, but I still see the same error on sl7 even after clearing my yum caches:
```
http://shoal.heprc.uvic.ca/repo/sl7x/prod/noarch/shoal-client-0.6.4-1.el7.centos.noarch.rpm: [Errno 14] HTTP Error 404 - Not Found
```

**Comment by colsond** [comment]
I'm not able to reproduce the error on sl7 or centos7. However I've rebuilt the sl7 repo again which should remove any references to non-existent files.

**Comment by DrDaveD** [comment]
Yes it works now, thanks.
